# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('starttime', models.TimeField(default='8:00')),
                ('endtime', models.TimeField(default='17:00')),
                ('sun', models.BooleanField(default=True)),
                ('mon', models.BooleanField(default=True)),
                ('tue', models.BooleanField(default=True)),
                ('wed', models.BooleanField(default=True)),
                ('thur', models.BooleanField(default=True)),
                ('fri', models.BooleanField(default=True)),
                ('sat', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
