# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='duration',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
